logoText = "Calvin Haynes's Blog"
logoType = "short" # long, short
description = "The site of Calvin Haynes's Blog"
custom_css = ["css/my.css", "css/fonts-zh.css", "css/fonts-code.css", "fontawesome/css/all.css", "css/pace.css"]
custom_js = ["js/pace.min.js"]
useFaviconGenerator = true # https://www.favicon-generator.org/
meta_image = "https://cdn.jsdelivr.net/gh/CalvinHaynes/ImageHub@main/Wallpaper/Calvin.1nljooch7gio.webp"
themecolor = "dark"

themeOptions = ["dark", "light", "solarized", "hacker", "kimbie"] 
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

viewportSize = "normal" # widest, wider, wide, normal, narrow
enableUiAnimation = true
hideSingleContentsWhenJSDisabled = false
enablePinnedPosts = true
minItemsToShowInTagCloud = 2 # Minimum items to show in tag cloud

# appbar
enableAppbarSearchIcon = true
enableAppbarLangIcon = false

# header
homeHeaderType = "typewriter" # text, img, slide, typewriter
hideHomeHeaderWhenMobile = false

# menu
showMobileMenuTerms = ["tags", "categories", "series"]

# search
enableSearch = true
enableSearchHighlight = true
searchResultPosition = "side" # side, main
searchContent = true # include content to search index
searchDistance = 100 # fuse option
searchThreshold = 0.4 # 0.0: exact match, 1.0: any match

# body
enableBreadcrumb = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20
writtenTimeIcon = "ğŸ“…"
modifiedTimeIcon = "ğŸ“"
readingTimeIcon = "â˜•"
authorIcon = "âœï¸"
pagePvIcon = "ğŸ‘€"
pinIcon = "ğŸ“Œ"
tagIcon = "ğŸ·ï¸"
publicationIcon = "ğŸ“š"
typeIcon = "ğŸ¯"

# whoami
myname = "Calvin Haynes"
email = "chx1006488386@163.com"
whoami = "æ…¢æ…¢èµ°æ‰ä¼šå¿«"
bioImageUrl = "https://cdn.jsdelivr.net/gh/CalvinHaynes/ImageHub@main/Icon/avatar.jpg"
useGravatar = false
location = "ChangChun, China"
organization = "JLU"
link = "https://www.jlu.edu.cn/"

# sidebar
enableBio = true
enableBioImage = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = false
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "outer" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "right"
tocLevels = ["h2", "h3", "h4"]
enableSidebarPostsByOrder = false

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = true
enableLangChange = false
enableThemeChange = true

# service
googleTagManager = "GTM-M2D7J9T" # GTM-XXXXXX
baiduAnalytics = "19839af18acbf1de9925cc2a79db76d9"
enableBusuanzi = true
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# rss
updatePeriod = "daily" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = true 
rssLimit = 10

# comment
enableComment = true
disqus_shortname = ""
commento = false

[telegram]
  enable = false
  siteId = ""
  dataLimit = 5

[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

[utterances]       # https://utteranc.es/
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments

[gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
  enable = true
  appId = '3ic2pCzBFIfn5Cm0X7DqPvPU-gzGzoHsz'
  appKey = 'qFnCvg6Ofy2la1mDziFN57wN'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm' 
  placeholder = 'è¯´ç‚¹ä»€ä¹ˆå§...'
  visitor = false

[changyan]
  changyanAppid = ""        # Changyan app id             # ç•…è¨€
  changyanAppkey = ""       # Changyan app key

[livere]
  livereUID = ""            # LiveRe UID                  # æ¥å¿…åŠ›

# Isso: https://posativ.org/isso/
[isso]
  enable = false
  scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions]
  email = "https://email.163.com/"
  phone = ""
  facebook = ""
  twitter = "https://twitter.com/CalvinHaynes412"
  github = "https://github.com/CalvinHaynes"
  stack-overflow = ""
  instagram = ""
  google-plus = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = ""
  pinterest = ""
  stack-exchange = ""
  telegram = "https://t.me/chx412523"
  steam = ""
  weibo = "https://weibo.com/u/5479707456"
  douban = "https://www.douban.com/people/201198470/"
  csdn = ""
  gitlab = ""
  mastodon = ""
  jianshu = ""
  zhihu = "https://www.zhihu.com/people/calvinhaynes"
  signal = ""
  whatsapp = ""
  matrix = ""
  xmpp = ""
  dev-to = ""
  gitea = ""
  google-scholar = ""

[donationOptions]
  enable = false
  alipay = "" 
  wechat = ""
  paypal = ""
  patreon = ""

[copyrightOptions]
  enableCopyrightLink = true 
  copyrightLink = "https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh"
  copyrightLinkImage = ""
  copyrightLinkText = "è‡ªç”±è½¬è½½-éå•†ç”¨-éè¡ç”Ÿ-ä¿æŒç½²å"


# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line", "pocket", "feedly", "hatena", "pinterest", "delicious", "google"]
[[share]]
  name = "facebook"
  username = ""
[[share]]
  name = "twitter"
[[share]]
  name = "weibo"
[[share]]
  name = "linkedin"

[[footerLinks]]
  name = ""
  link = ""
[[footerLinks]]
  name = ""
  link = ""